const app = document.querySelector("#app");
const config = window.EN_MARCHA_SUPABASE_CONFIG || {};
// The Supabase CDN exposes `window.supabase`; use a distinct local client name to avoid redeclaring that global.
const supabaseClient = window.supabase?.createClient?.(config.url, config.publishableKey);

const STATUS = {
  pending: ["Pendiente", "#a0aaba"],
  progress: ["En curso", "#8b7cf6"],
  waiting: ["En espera", "#f5a75a"],
  completed: ["Completado", "#55d6ae"],
  skipped: ["No publicado", "#e57e7e"],
};
const PROFILES = {
  "dinero-sin-filtro": { id: "dinero-sin-filtro", name: "Dinero Sin Filtro", color: "#55d6ae", meta: "Español · 1.700–1.800 palabras · Vídeo diario", flow: "Guion aprobado → SEO y prompts → 3 PDFs" },
  "why-things": { id: "why-things", name: "WhyThings", color: "#f5a75a", meta: "Inglés · 1.000–1.100 palabras · 5–8 minutos", flow: "Guion aprobado → prompts → SEO → 3 PDFs" },
};

let state = { session: null, workspace: null, channels: [], entries: [], page: "today", date: isoDate(new Date()), month: new Date(), modal: null, message: "", error: "", channelFilter: "all", statusFilter: "all" };
let realtime;

function isoDate(date) { return date.toISOString().slice(0, 10); }
function parseDate(value) { return new Date(`${value}T12:00:00`); }
function addDays(value, days) { const date = parseDate(value); date.setDate(date.getDate() + days); return isoDate(date); }
function escapeHtml(value = "") { return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
function formatDate(value, options = { weekday: "long", day: "numeric", month: "long" }) { return new Intl.DateTimeFormat("es-ES", options).format(parseDate(value)); }
function capitalise(value) { return value.charAt(0).toUpperCase() + value.slice(1); }
function channel(id) { return state.channels.find((item) => item.id === id) || PROFILES[id] || { name: "Canal", color: "#a0aaba" }; }
function icon(name) {
  const shapes = { spark: '<path d="m12 3 1.7 5.3L19 10l-5.3 1.7L12 17l-1.7-5.3L5 10l5.3-1.7L12 3Z"/><path d="m19 16 .7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7L19 16Z"/>', plus: '<path d="M12 5v14M5 12h14"/>', check: '<path d="m5 12 4 4L19 6"/>', calendar: '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>', history: '<path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 3v6h6M12 7v5l3 2"/>', settings: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.1 2.1-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.5v.2h-3v-.2a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.9.3l-.1.1L6.6 17l.1-.1A1.7 1.7 0 0 0 7 15a1.7 1.7 0 0 0-1.5-1H5v-3h.2A1.7 1.7 0 0 0 6.7 10 1.7 1.7 0 0 0 6.4 8l-.1-.1L8.4 5.8l.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.5v-.2h3v.2a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.9-.3l.1-.1 2.1 2.1-.1.1A1.7 1.7 0 0 0 19.1 10a1.7 1.7 0 0 0 1.5 1h.2v3h-.2a1.7 1.7 0 0 0-1.2 1Z"/>', arrowLeft: '<path d="m15 18-6-6 6-6"/>', arrowRight: '<path d="m9 18 6-6-6-6"/>', trash: '<path d="M3 6h18M8 6V4h8v2m-9 0 1 14h8l1-14M10 10v6M14 10v6"/>', close: '<path d="m6 6 12 12M18 6 6 18"/>', file: '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6Z"/><path d="M14 2v6h6M8 13h8M8 17h5"/>' };
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${shapes[name] || ""}</svg>`;
}

function withTimeout(promise, milliseconds) {
  return Promise.race([
    promise,
    new Promise((_, reject) => setTimeout(() => reject(new Error("timeout")), milliseconds)),
  ]);
}

async function boot() {
  if (!(config.url && config.publishableKey && supabaseClient)) { state.error = "No se pudo cargar la conexión compartida. Recarga la página y comprueba tu conexión a internet."; render(); return; }

  // Render the sign-in page immediately. A slow Supabase response must never block the whole app.
  render();
  if ("serviceWorker" in navigator) navigator.serviceWorker.register("./service-worker.js?v=3").catch(() => {});

  try {
    const { data } = await withTimeout(supabaseClient.auth.getSession(), 4000);
    state.session = data.session;
    if (state.session) await loadMemberships();
  } catch {
    state.message = "La comprobación automática ha tardado demasiado. Puedes introducir tu correo para entrar igualmente.";
  }

  supabaseClient.auth.onAuthStateChange(async (_event, session) => {
    state.session = session;
    state.workspace = null;
    state.entries = [];
    state.channels = [];
    if (session) await loadMemberships();
    render();
  });
  render();
}

async function loadMemberships() {
  const { data, error } = await supabaseClient.from("workspace_members").select("role, workspaces(id, name, invite_code)").eq("user_id", state.session.user.id);
  if (error) { state.error = "No se pudo abrir el espacio. Comprueba que el SQL se haya ejecutado."; return; }
  const workspaces = (data || []).map((row) => Array.isArray(row.workspaces) ? row.workspaces[0] : row.workspaces).filter(Boolean);
  const remembered = localStorage.getItem("en-marcha-workspace");
  state.workspace = workspaces.find((item) => item.id === remembered) || workspaces[0] || null;
  if (state.workspace) { localStorage.setItem("en-marcha-workspace", state.workspace.id); await ensureChannels(); await loadData(); subscribe(); }
}
async function ensureChannels() {
  const rows = Object.values(PROFILES).map((item) => ({ workspace_id: state.workspace.id, id: item.id, name: item.name, color: item.color }));
  await supabaseClient.from("channels").upsert(rows, { onConflict: "workspace_id,id", ignoreDuplicates: true });
}
async function loadData() {
  const [channels, entries] = await Promise.all([
    supabaseClient.from("channels").select("id,name,color").eq("workspace_id", state.workspace.id).order("created_at"),
    supabaseClient.from("video_entries").select("id,channel_id,title,scheduled_for,status,completed_at").eq("workspace_id", state.workspace.id).order("scheduled_for"),
  ]);
  if (channels.error || entries.error) { state.error = "No se pudieron cargar los datos compartidos."; return; }
  state.channels = channels.data || [];
  state.entries = (entries.data || []).map((item) => ({ id: item.id, channelId: item.channel_id, title: item.title, date: item.scheduled_for, status: item.status, completedAt: item.completed_at }));
}
function subscribe() {
  if (realtime) supabaseClient.removeChannel(realtime);
  realtime = supabaseClient.channel(`team-${state.workspace.id}`).on("postgres_changes", { event: "*", schema: "public", table: "video_entries", filter: `workspace_id=eq.${state.workspace.id}` }, async () => { await loadData(); render(); }).on("postgres_changes", { event: "*", schema: "public", table: "channels", filter: `workspace_id=eq.${state.workspace.id}` }, async () => { await loadData(); render(); }).subscribe();
}

function render() {
  if (state.error) { app.innerHTML = `<main class="access-page"><section class="access-card"><div class="access-mark">${icon("spark")}</div><h1>Revisa la conexión</h1><p>${escapeHtml(state.error)}</p></section></main>`; return; }
  if (!state.session) { app.innerHTML = signInView(); return; }
  if (!state.workspace) { app.innerHTML = workspaceView(); return; }
  app.innerHTML = `<div class="app-shell">${sidebar()}<main class="main"><header class="topbar"><div class="crumb">${icon("spark")}<span>Espacio compartido · ${escapeHtml(state.workspace.name)}</span></div><button class="primary-button" data-action="new-entry">${icon("plus")} Nuevo vídeo</button></header><section class="view">${state.page === "calendar" ? calendarView() : state.page === "history" ? historyView() : state.page === "settings" ? settingsView() : todayView()}</section></main></div>${state.modal ? modal() : ""}<div class="toast" id="toast"></div>`;
}
function signInView() { return `<main class="access-page"><section class="access-card"><div class="access-mark">${icon("spark")}</div><p class="eyebrow">EN MARCHA · ESPACIO COMPARTIDO</p><h1>Tu producción, en el mismo sitio.</h1><p>Entra con tu correo. Tú y tu compañera veréis los cambios de inmediato.</p><form id="login-form" class="access-form"><label for="email">Correo electrónico</label><input id="email" name="email" type="email" required placeholder="tu@email.com"/><button class="primary-button access-button">Enviar enlace de acceso</button></form>${state.message ? `<p class="access-message">${escapeHtml(state.message)}</p>` : ""}</section></main>`; }
function workspaceView() { return `<main class="access-page"><section class="access-card workspace-card"><div class="access-mark">${icon("spark")}</div><p class="eyebrow">EN MARCHA · ESPACIO COMPARTIDO</p><h1>Prepara vuestro espacio.</h1><p>Crea el panel una sola vez. Tu compañera entrará después con el código de ocho caracteres.</p><div class="workspace-choice-grid"><form id="create-workspace" class="workspace-choice"><h2>Crear espacio</h2><p>Para la primera persona del equipo.</p><label>Nombre</label><input name="name" value="Producción YouTube" required maxlength="80"/><button class="primary-button">Crear y continuar</button></form><form id="join-workspace" class="workspace-choice"><h2>Unirme al equipo</h2><p>Pega el código que te han enviado.</p><label>Código</label><input name="code" required maxlength="8" placeholder="A1B2C3D4"/><button class="secondary-button">Unirme</button></form></div>${state.message ? `<p class="access-message">${escapeHtml(state.message)}</p>` : ""}</section></main>`; }
function sidebar() { const tabs = [["today", "Hoy", "file"], ["calendar", "Calendario", "calendar"], ["history", "Historial", "history"], ["settings", "Ajustes", "settings"]]; return `<aside class="sidebar"><div class="brand"><span class="brand-mark">${icon("spark")}</span><span>En Marcha<small>Control de contenidos</small></span></div><p class="nav-label">Espacio de trabajo</p><nav class="nav-group">${tabs.map(([id,label,shape]) => `<button class="nav-item ${state.page === id ? "active" : ""}" data-page="${id}">${icon(shape)}<span>${label}</span></button>`).join("")}</nav><p class="nav-label">Tus canales</p><div class="channel-list">${state.channels.map((item) => `<button class="channel-link" data-channel-filter="${item.id}"><i class="channel-dot" style="background:${item.color}"></i>${escapeHtml(item.name)}</button>`).join("")}</div><div class="sidebar-footer"><strong>Espacio compartido</strong>Cambios sincronizados en tiempo real.</div></aside>`; }
function dateSwitcher() { return `<div class="date-switcher"><button data-day="-1">${icon("arrowLeft")}</button><input type="date" data-date value="${state.date}"/><button data-day="1">${icon("arrowRight")}</button></div>`; }
function todayView() { const entries = state.entries.filter((item) => item.date === state.date); const completed = entries.filter((item) => item.status === "completed").length; const active = entries.filter((item) => ["progress","waiting"].includes(item.status)).length; const future = state.entries.filter((item) => item.date > state.date && !["completed","skipped"].includes(item.status)).slice(0,4); return `<div class="page-intro"><div><h1>${capitalise(formatDate(state.date))}</h1><p class="subtext">Un vídeo a la vez. Lo que importa es avanzar.</p></div>${dateSwitcher()}</div><div class="stat-grid"><article class="stat-card ink"><span class="stat-label">Previstos</span><div class="stat-value">${entries.length}</div><p class="stat-detail">para este día</p></article><article class="stat-card"><span class="stat-label">Completados</span><div class="stat-value">${completed}</div><p class="stat-detail">vídeos terminados</p></article><article class="stat-card purple"><span class="stat-label">En movimiento</span><div class="stat-value">${active}</div><p class="stat-detail">en curso o esperando</p></article><article class="stat-card orange"><span class="stat-label">Pendientes</span><div class="stat-value">${entries.filter((item) => item.status === "pending").length}</div><p class="stat-detail">por empezar</p></article></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><div class="panel-title"><span class="panel-title-icon">${icon("file")}</span><div><h2>Lo que toca</h2><p class="subtext">Marca cada vídeo cuando esté listo.</p></div></div><button class="text-button" data-action="new-entry">+ Añadir</button></div>${entries.length ? `<div class="task-list">${entries.map(task).join("")}</div>` : empty()}</section><aside class="side-stack"><section class="panel progress-card"><h2>Ritmo del día</h2><p class="subtext">${completed} de ${entries.length} completados.</p><div class="progress-wrap"><div class="progress-ring" style="--progress:${entries.length ? completed / entries.length * 360 : 0}deg"><strong>${entries.length ? Math.round(completed / entries.length * 100) : 0}%</strong></div><div class="progress-copy"><strong>${completed === entries.length && entries.length ? "Día despejado" : "Sigue con el siguiente paso"}</strong><span>El equipo ve el avance al instante.</span></div></div></section><section class="panel"><div class="panel-head"><div><h2>Próximamente</h2><p class="subtext">La siguiente cola.</p></div></div><div class="next-list">${future.length ? future.map(next).join("") : '<div class="empty-state"><p>No hay nada pendiente.</p></div>'}</div></section></aside></div>`; }
function task(item) { const [label] = STATUS[item.status]; const current = channel(item.channelId); return `<article class="task-card"><span class="task-state ${item.status}">${item.status === "completed" ? icon("check") : icon("file")}</span><div class="task-content"><span class="channel-pill"><i style="background:${current.color}"></i>${escapeHtml(current.name)}</span><p class="task-title">${escapeHtml(item.title)}</p><div class="task-meta"><span>${label}</span></div></div><div class="task-actions"><select class="status-select" data-status="${item.id}">${Object.entries(STATUS).map(([id, status]) => `<option value="${id}" ${item.status === id ? "selected" : ""}>${status[0]}</option>`).join("")}</select>${item.status !== "completed" ? `<button class="complete-button" data-complete="${item.id}">Completar</button>` : ""}<button class="delete-button" data-delete="${item.id}">${icon("trash")}</button></div></article>`; }
function empty() { return `<div class="empty-state"><div class="empty-symbol">${icon("check")}</div><h3>Sin vídeos para este día</h3><p>Añade lo que toca publicar y vuelve para marcarlo como terminado.</p><button class="primary-button" data-action="new-entry">${icon("plus")} Añadir vídeo</button></div>`; }
function next(item) { const current = channel(item.channelId); const day = parseDate(item.date); return `<div class="next-item"><div class="next-date">${day.getDate()}<small>${new Intl.DateTimeFormat("es-ES",{month:"short"}).format(day).replace(".","")}</small></div><div class="next-copy"><strong>${escapeHtml(item.title)}</strong><span><i class="channel-dot" style="background:${current.color};display:inline-block;margin-right:4px"></i>${escapeHtml(current.name)}</span></div></div>`; }
function calendarView() { const month = state.month; const first = new Date(month.getFullYear(), month.getMonth(), 1); const offset = (first.getDay() + 6) % 7; const start = new Date(month.getFullYear(), month.getMonth(), 1 - offset); const cells = Array.from({length:42}, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); const value = isoDate(date); const count = state.entries.filter((item) => item.date === value).length; return `<button class="day-cell ${date.getMonth() !== month.getMonth() ? "other-month" : ""} ${value === state.date ? "selected" : ""}" data-select-date="${value}"><span class="day-number">${date.getDate()}</span>${count ? `<span class="day-count">${count}</span>` : ""}</button>`; }).join(""); return `<div class="page-intro"><div><h1>Tu calendario</h1><p class="subtext">Planifica antes de que llegue el día.</p></div><button class="primary-button" data-action="new-entry">${icon("plus")} Nuevo vídeo</button></div><section class="panel calendar-panel"><div class="month-nav"><h2>${capitalise(new Intl.DateTimeFormat("es-ES",{month:"long",year:"numeric"}).format(month))}</h2><div class="month-actions"><button data-month="-1">${icon("arrowLeft")}</button><button data-month="1">${icon("arrowRight")}</button></div></div><div class="calendar-grid">${["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map((name) => `<span class="weekday">${name}</span>`).join("")}${cells}</div></section>`; }
function historyView() { const entries = state.entries.filter((item) => (state.channelFilter === "all" || item.channelId === state.channelFilter) && (state.statusFilter === "all" || item.status === state.statusFilter)).sort((a,b) => b.date.localeCompare(a.date)); return `<div class="page-intro"><div><h1>Historial</h1><p class="subtext">Todo lo programado, hecho y pendiente.</p></div><div class="filters"><select data-filter="channel" class="filter-select"><option value="all">Todos los canales</option>${state.channels.map((item) => `<option value="${item.id}" ${state.channelFilter === item.id ? "selected" : ""}>${escapeHtml(item.name)}</option>`).join("")}</select><select data-filter="status" class="filter-select"><option value="all">Todos los estados</option>${Object.entries(STATUS).map(([id,item]) => `<option value="${id}" ${state.statusFilter === id ? "selected" : ""}>${item[0]}</option>`).join("")}</select></div></div><section class="panel history-panel"><div class="history-table-wrap"><table class="history-table"><thead><tr><th>Vídeo</th><th>Canal</th><th>Fecha</th><th>Estado</th></tr></thead><tbody>${entries.map((item) => { const current = channel(item.channelId); const status = STATUS[item.status]; return `<tr><td class="title-cell"><strong>${escapeHtml(item.title)}</strong></td><td><span class="channel-pill"><i style="background:${current.color}"></i>${escapeHtml(current.name)}</span></td><td>${capitalise(new Intl.DateTimeFormat("es-ES",{day:"numeric",month:"short"}).format(parseDate(item.date)))}</td><td><span class="status-badge ${item.status}"><i style="background:${status[1]}"></i>${status[0]}</span></td></tr>`; }).join("")}</tbody></table></div></section>`; }
function settingsView() { return `<div class="page-intro"><div><h1>Ajustes</h1><p class="subtext">El espacio se sincroniza entre las dos personas del equipo.</p></div></div><div class="settings-grid"><section class="panel settings-panel team-panel"><span class="shared-label">ESPACIO COMPARTIDO</span><h2>${escapeHtml(state.workspace.name)}</h2><p>Comparte este código con tu compañera para que se una al mismo panel.</p><div class="invite-code"><span>${escapeHtml(state.workspace.invite_code)}</span><button class="secondary-button" data-action="copy-code">Copiar código</button></div><div class="settings-actions"><button class="secondary-button" data-action="logout">Cerrar sesión</button></div></section><section class="panel settings-panel"><h2>Canales</h2><div class="channel-management">${state.channels.map((item) => { const profile = PROFILES[item.id]; return `<div class="channel-manage-row"><span class="channel-avatar" style="background:${item.color}">${escapeHtml(item.name[0])}</span><div class="channel-manage-copy"><strong>${escapeHtml(item.name)}</strong><small>${profile?.meta || "Canal personalizado"}</small></div><span class="channel-count">${state.entries.filter((entry) => entry.channelId === item.id).length} vídeos</span></div>`; }).join("")}</div></section><section class="panel settings-panel production-profiles"><h2>Guías de producción</h2><div class="profile-grid">${Object.values(PROFILES).map((item) => `<article class="profile-card"><div class="profile-card-head"><span class="profile-marker" style="background:${item.color}"></span><div><h3>${item.name}</h3><span>${item.meta}</span></div></div><small>${item.flow}</small></article>`).join("")}</div></section></div>`; }
function modal() { return `<div class="modal-backdrop" data-close-modal><section class="modal" onclick="event.stopPropagation()"><div class="modal-head"><div><h2>Nuevo vídeo</h2><p>Guarda qué toca publicar y el equipo lo verá al instante.</p></div><button class="icon-button" data-close-modal>${icon("close")}</button></div><form id="entry-form"><div class="form-field"><label>Tema o título</label><input name="title" required maxlength="150" autofocus placeholder="Ej. Cómo tu cerebro gasta tu nómina"/></div><div class="form-grid"><div class="form-field"><label>Canal</label><select name="channelId">${state.channels.map((item) => `<option value="${item.id}">${escapeHtml(item.name)}</option>`).join("")}</select></div><div class="form-field"><label>Fecha</label><input name="date" type="date" value="${state.date}" required/></div></div><div class="form-field"><label>Estado</label><select name="status">${Object.entries(STATUS).map(([id,item]) => `<option value="${id}">${item[0]}</option>`).join("")}</select></div><div class="form-actions"><button class="cancel-button" type="button" data-close-modal>Cancelar</button><button class="primary-button">Guardar vídeo</button></div></form></section></div>`; }

async function login(email) { state.message = "Enviando enlace…"; render(); const { error } = await supabaseClient.auth.signInWithOtp({ email, options: { emailRedirectTo: `${location.origin}${location.pathname}` } }); state.message = error ? "No se pudo enviar el enlace. Prueba de nuevo." : "Revisa tu correo y abre el enlace para entrar."; render(); }
async function createWorkspace(name) { const { data, error } = await supabaseClient.rpc("create_workspace", { workspace_name: name }); if (error || !data?.[0]) { state.message = "No se pudo crear el espacio. Comprueba el SQL de Supabase."; render(); return; } state.workspace = data[0]; localStorage.setItem("en-marcha-workspace", state.workspace.id); await ensureChannels(); await loadData(); subscribe(); render(); }
async function joinWorkspace(code) { const { data, error } = await supabaseClient.rpc("join_workspace", { code_to_join: code.trim() }); if (error || !data?.[0]) { state.message = "No encontramos ese código. Revísalo y prueba otra vez."; render(); return; } state.workspace = data[0]; localStorage.setItem("en-marcha-workspace", state.workspace.id); await ensureChannels(); await loadData(); subscribe(); render(); }
async function saveEntry(form) { const record = { workspace_id: state.workspace.id, channel_id: form.get("channelId"), title: String(form.get("title")).trim(), scheduled_for: form.get("date"), status: form.get("status"), created_by: state.session.user.id, updated_by: state.session.user.id, completed_at: form.get("status") === "completed" ? new Date().toISOString() : null }; const { error } = await supabaseClient.from("video_entries").insert(record); if (error) toast("No se pudo guardar el vídeo."); else { state.modal = null; await loadData(); render(); toast("Vídeo añadido al espacio compartido."); } }
async function changeStatus(id, status) { const { error } = await supabaseClient.from("video_entries").update({ status, updated_by: state.session.user.id, completed_at: status === "completed" ? new Date().toISOString() : null }).eq("id", id).eq("workspace_id", state.workspace.id); if (error) toast("No se pudo guardar el cambio."); }
async function deleteEntry(id) { if (!confirm("¿Eliminar este vídeo?")) return; await supabaseClient.from("video_entries").delete().eq("id", id).eq("workspace_id", state.workspace.id); }
function toast(message) { const node = document.querySelector("#toast"); if (!node) return; node.textContent = message; node.classList.add("show"); setTimeout(() => node.classList.remove("show"), 2600); }

document.addEventListener("click", async (event) => { const target = event.target.closest("[data-page],[data-action],[data-day],[data-month],[data-select-date],[data-complete],[data-delete],[data-close-modal],[data-channel-filter]"); if (!target) return; if (target.dataset.page) { state.page = target.dataset.page; render(); } if (target.dataset.action === "new-entry") { state.modal = true; render(); } if (target.dataset.action === "copy-code") { await navigator.clipboard.writeText(state.workspace.invite_code); toast("Código de invitación copiado."); } if (target.dataset.action === "logout") await supabaseClient.auth.signOut(); if (target.dataset.day) { state.date = addDays(state.date, Number(target.dataset.day)); render(); } if (target.dataset.month) { state.month = new Date(state.month.getFullYear(), state.month.getMonth() + Number(target.dataset.month), 1); render(); } if (target.dataset.selectDate) { state.date = target.dataset.selectDate; state.page = "today"; render(); } if (target.dataset.complete) await changeStatus(target.dataset.complete, "completed"); if (target.dataset.delete) await deleteEntry(target.dataset.delete); if (target.hasAttribute("data-close-modal")) { state.modal = null; render(); } if (target.dataset.channelFilter) { state.channelFilter = target.dataset.channelFilter; state.page = "history"; render(); } });
document.addEventListener("change", async (event) => { if (event.target.dataset.status) await changeStatus(event.target.dataset.status, event.target.value); if (event.target.dataset.date) { state.date = event.target.value; render(); } if (event.target.dataset.filter === "channel") { state.channelFilter = event.target.value; render(); } if (event.target.dataset.filter === "status") { state.statusFilter = event.target.value; render(); } });
document.addEventListener("submit", async (event) => { event.preventDefault(); if (event.target.id === "login-form") return login(new FormData(event.target).get("email")); if (event.target.id === "create-workspace") return createWorkspace(new FormData(event.target).get("name")); if (event.target.id === "join-workspace") return joinWorkspace(new FormData(event.target).get("code")); if (event.target.id === "entry-form") return saveEntry(new FormData(event.target)); });
boot();
